version: "3.2"
services:
  proxy:
    image: registry.berr.dev/nginx:deployed
    restart: always
    logging:
      driver: json-file
    environment:    
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/data/home_server/data/certs:/certs:ro
    ports:
    - 80:80
    - 443:443
    depends_on:
      - priv_syncthing

  
  priv_syncthing:
    image: registry.berr.dev/syncthing:deployed
    restart: always
    logging:
      driver: json-file
    ports:
      - 22000:22000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/home_server/data/syncthing:/config
      - /mnt/data/Downloads/syncthing:/data/downloads
    environment:    
      - PUID=0
      - GUID=0

