version: "3.2"
services:
  proxy:
    image: 'nginx:1.20.0-alpine'
    environment:    
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/data_fast/home_server/data/certs:/certs:ro
    ports:
    - 80:80
    - 443:443
    depends_on:
      - priv_syncthing

  
  priv_syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    restart: unless-stopped
    logging:
      driver: json-file
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data_fast/home_server/data/syncthing:/config
      - /mnt/data_slow/Downloads/syncthing:/data/downloads
    environment:    
      - PUID=0
      - GUID=0

