version: "3.2"
services:
  proxy:
    image: 'nginx:1.20.0-alpine'
    restart: always
    logging:
      driver: json-file
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/data/home_server/data/certs:/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - priv_registry

  priv_registry:
    restart: always
    image: registry:2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/home_server/data/certs:/certs:ro
      - /mnt/data/home_server/data/registry:/var/lib/registry
    logging:
      driver: json-file