version: "3.2"
services:
  proxy:
    image: registry.berr.dev/nginx:deployed
    restart: always
    logging:
      driver: json-file
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/data/home_server/data/certs:/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - priv_grafana

  priv_grafana:
    image: registry.berr.dev/grafana:deployed
    restart: always
    logging:
      driver: json-file
    user: 0:0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/home_server/data/grafana:/var/lib/grafana
      - ./config/provisioning:/etc/grafana/provisioning
      - ./config/dashboards:/etc/dashboards

    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Sao_Paulo

   