---
version: "2.1"
services:
  proxy:
    image: registry.berr.dev/nginx:deployed
    restart: always
    logging:
      driver: json-file
    environment:    
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/data/home_server/data/certs:/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - priv_homeassistant

  priv_homeassistant:
    image: homeassistant/home-assistant:2024.3
    restart: always
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/home_server/data/home_assistant/config:/config
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
    privileged: true

