version: "3.2"
services:
  proxy:
    image: registry.berr.dev/nginx:deployed
    restart: always
    logging:
      driver: json-file
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/data/home_server/data/certs:/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - priv_sonarr
      - priv_radarr
      - priv_lidarr
      - priv_bazarr
      - priv_prowlarr

  priv_sonarr:
    image: registry.berr.dev/sonarr:deployed
    restart: always
    logging:
      driver: json-file
    environment:    
      - PUID=0
      - GUID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/home_server/data/sonarr:/config
      - /mnt/data/Media/series/:/data/series
      - /mnt/data/Downloads/syncthing:/data/downloads

  priv_radarr:
    image: registry.berr.dev/radarr:deployed
    restart: always
    logging:
      driver: json-file
    environment:    
      - PUID=0
      - GUID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/home_server/data/radarr:/config
      - /mnt/data/Media/movies/:/data/movies
      - /mnt/data/Downloads/syncthing:/data/downloads

  priv_lidarr:
    image: registry.berr.dev/lidarr:deployed
    restart: always
    logging:
      driver: json-file
    environment:    
      - PUID=0
      - GUID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/home_server/data/lidarr:/config
      - /mnt/data/Media/music/:/data/music
      - /mnt/data/Downloads/syncthing:/data/downloads

  priv_bazarr:
    image: registry.berr.dev/bazarr:deployed
    restart: always
    logging:
      driver: json-file
    environment:    
      - PUID=0
      - GUID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/home_server/data/bazarr:/config
      - /mnt/data/Media/series/:/data/series
      - /mnt/data/Media/movies/:/data/movies

  priv_prowlarr:
    image: registry.berr.dev/prowlarr:deployed
    restart: always
    logging:
      driver: json-file
    environment:    
      - PUID=0
      - GUID=0
    volumes:
      - /mnt/data/home_server/data/prowlarr:/config

