version: "3.2"
services:
  proxy:
    image: registry.berr.dev/nginx:deployed
    environment:    
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/data/home_server/data/certs:/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - priv_logseq

  priv_logseq:
    image: registry.berr.dev/logseq-webapp:deployed
    logging:
      driver: json-file
