---
- name: Install docker
  hosts: docker_services
  remote_user: root
  
  tasks:
  - name: Update apt and install gpg and pip
    ansible.builtin.apt:
      name: 
        - gpg
        - pip
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/debian bullseye stable
      state: present

  - name: Install docker-ce
    ansible.builtin.apt:
      name:
        - docker-ce
      state: latest
      update_cache: true
      clean: true

  - name: Install Docker Module for Python
    pip:
      name:
       - docker<7.0
       - docker-compose==1.29
