---
- name: Install Pihole
  hosts: pihole
  remote_user: root

  tasks:
  - name: Create pihole directories
    ansible.builtin.file:
      path: /etc/pihole
      state: directory
      mode: '0755'

  - name: Create custom hosts directory
    ansible.builtin.file:
      path: /etc/pihole/custom_hosts
      state: directory
      mode: '0755'
  
  - name: Copy configuration file
    ansible.builtin.copy:
      src: "../config/pihole/setupVars.conf"
      dest: /etc/pihole/setupVars.conf

  - name: Download Pihole installer
    delegate_to: localhost
    get_url:
      url: "https://install.pi-hole.net"
      dest: "/tmp/install_pihole.sh"

  - name: Install pihole
    ansible.builtin.script:
      cmd: /tmp/install_pihole.sh --unattended

  - name: Copy DHCP reservations
    ansible.builtin.copy:
      src: "../private/dhcp_reservations"
      dest: /etc/dnsmasq.d/10-dhcp_reservations

  - name: Copy CNAMEs
    ansible.builtin.copy:
      src: "../config/pihole/cnames"
      dest: /etc/dnsmasq.d/11-cnames

  - name: Copy hosts in NUC
    ansible.builtin.copy:
      src: "../config/pihole/nuc_hosts"
      dest: /etc/pihole/custom_hosts/01-nuc_hosts

  - name: Copy hosts in NAS
    ansible.builtin.copy:
      src: "../config/pihole/nas_hosts"
      dest: /etc/pihole/custom_hosts/02-nas_hosts

  - name: Copy extra hosts
    ansible.builtin.copy:
      src: "../config/pihole/extra_hosts"
      dest: /etc/pihole/custom_hosts/03-extra_hosts

  - name: Merge files into a single custom.list
    ansible.builtin.assemble:
      src: /etc/pihole/custom_hosts
      dest: /etc/pihole/custom.list

  - name: Restart DHCP
    ansible.builtin.systemd:
      name: pihole-FTL
      state: restarted
