version: "3.2"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    restart: always
    logging:
      driver: json-file
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/config:/config
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Sao_Paulo
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
